name: CI-GB
on:
  push:
    branches:
      - master
      - main
  pull_request:

env:
  TZ: "Asia/Taipei"

jobs:
  gb:
    strategy:
      matrix:
        go-version: [ '1.22' ]
    name: code-test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Timezone
        uses: szenius/set-timezone@v1.1
        with:
          timezoneLinux: "Asia/Taipei"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Golang ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: false

      - name: Test
        run: go test ./... -race

      - name: Coverage
        run: go test ./... -race -coverprofile=coverage.out -covermode=atomic -coverpkg=./...,ghostbb.io/gb/...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
        env:
          slug: go-ghostbb/gb
          flags: go-${{ matrix.go-version }}