name: GB AutoCreating SubMod Tags And Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  TZ: Asia/Shanghai

jobs:
  build:
    name: Auto Creating Tags And Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github Code
        uses: actions/checkout@v4

      - name: Auto Creating Tags For Contrib Packages
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "tagrobot@ghostbb.io"
          git config --global user.name  "TagRobot"
          
          # auto create tags for contrib packages.
          for file in `find contrib -name go.mod`; do
              tag=$(dirname $file)/$GITHUB_REF_NAME
              git tag $tag
              git push origin $tag
          done
          
          # auto create tag for cli tool
          for file in `find cmd -name go.mod`; do
              tag=$(dirname $file)/$GITHUB_REF_NAME
              git tag $tag
              git push origin $tag
          done

      - name: Create Github Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          name: GB Release ${{ github.ref }}
          draft: false
          prerelease: false